Update convert.py
lifeomic/foundation-xml-fhir pull request #17
Opened 2019-11-08 18:28 UTC by kwood16

Correction of misspelling in write_vcf function.

2019-11-08 18:33 UTC, mschroering approved these changes

2021-02-24 16:31 UTC, jairav approved these changes

2021-02-24 16:34 UTC, jairav requested changes
Need to investigate any downstream effects before this is approved or merged.

2021-02-24 20:59 UTC, rcdilorenzo commented
Agreed. I definitely have no idea in this case. We'll have to check it out. Tag me when you know more.

2021-02-25 15:10 UTC, rcdilorenzo reviewed
Agreed. I definitely have no idea in this case. We'll have to check it out. Tag me when you know more.

2021-02-25 16:26 UTC, closed without merging